# The error function is being used only for debugging purposes
def error(*messages):
    # print("Error:", *messages)
    pass


def debug(*messages):
    # print("Debug:", *messages)
    pass


configurations = {"Automation_Tool": "Tosca"}
